### ISSUE TITLE
No Weather Restrictions

### ISSUE THREAD

**Issue by MGDHati** [Ottermandias/GatherBuddy#110]
So I love using GatherBuddy, I really do but I have noticed when trying to catch the Legendary Fish for the Feast of Famine that so far three Legendary Fish have been listed with not having Weather Restrictions. I had to Google to find out why I could not catch one of them and to make sure these two new ones were truly always I Google as well. The Nanmitaro needs to be done during Thunder or Thunderstorm. The other two that I know so far are Shonisaurus which must be caught transition from Clear or fair into Blizzard. And the last one I have for now is Kuno the Killer who needs Gloom to be caught. The catch Next up saying always with there being a thing saying No Weather Restriction hurts my soul as GatherBuddy is good when it comes to other fish about it.

**Comment by Ottermandias** [comment]
Neither of those fish has any restrictions themselves - this is directly from the game data, so its infallible.
The fish they need you to catch for Intuition or Mooching have restrictions, but those restrictions do not extend to the fish themselves. 
This is a relevant distinction, because you can throw out your rod during a fishes uptime, then catch it outside its uptime.
I.e. you throw out your rod with a Cloud Cutter during snow, but the weather changes during your wait time, then you catch Mahar, and throw him out again - it's not Blizzarding anymore, but you can still catch Shonisaurus.

That is why each of the three fish you listed has a differently colored uptime text and displays an "Uptime Dependency" warning.

![image](https://user-images.githubusercontent.com/70807659/183593705-cc0f2830-f434-4f90-ae1b-e51b76771c69.png)
