### ISSUE TITLE
Colours too similar (Timed fish and similar).

### ISSUE THREAD

**Issue by Myojine** [Ottermandias/GatherBuddy#19]
Quite "new" to github so idk if it's fine to post suggestions here, this is an issue for me none the less so I guess it goes here afterall.

The green and yellow in "Timed fish" looks 100% the same, would it be possible to maybe make one of the colours distinctively darker than the other so colourblind people can use the addon?

**Comment by Ottermandias** [comment]
https://github.com/Ottermandias/GatherBuddy/commit/14b824888ba75dc39deca357599a7c77bb19cf45

Yeah, that would be possible. I'll do a dalamud-repo release today, when it's updated you can set the colors yourself. (only for the timed fish tab though, I did not fiddle with the fish timer yet, because there are multiple layers of transparency there - maybe later.
