### ISSUE TITLE
Ocean fishing shows many catchable fish as uncatchable

### ISSUE THREAD

**Issue by Z-95** [Ottermandias/GatherBuddy#51]
When Ocean Fishing many of the fish on the list are colored red when they are actually catchable.

I did a lot of ocean fishing the past summer so I had lots of catch data saved (and I remember how the fishing catch timer window used to look). Took a fishing break for a few months but now when in ocean fishing 4-5 of the fish are always marked red but I can still catch them (like the spectral fish to trigger a current). Also since they are marked red my saved catch times are not displayed.

Took some screen snips to show the issue (both in a normal current and a spectral current):
![ocean1](https://user-images.githubusercontent.com/3287145/147956107-9a1d2f16-f8f4-4f0d-8fb3-3f786c77ef58.PNG)
![ocean2](https://user-images.githubusercontent.com/3287145/147956120-b7be1066-efee-43f5-bed5-94cac8f97d9e.PNG)

**Comment by Ottermandias** [comment]
That's because they have no associated catch data for their limits (the game has information that they are weather- or time-restricted, but not what the concrete restrictions are).
GatherBuddy knows they should have restrictions, but not what they are, so they're displayed as unavailable.

This will be changed in the next version so that all oceanfish should always be displayed as available, since they also depend on  ingame weather that's not based on server time, which I don't intend to support.
