### ISSUE TITLE
Intuition/mooch availability not reflected in fish uptime clock

### ISSUE THREAD

**Issue by NotNite** [Ottermandias/GatherBuddy#64]
I noticed this while going for the Feast of Famine quest. GatherBuddy marks them in a different color, but still says "Always Up" even if a dependency isn't available. This means I have to pin several more fish and makes it a hassle to catch.

It'd be nice if it could look forward to see when all requirements would be satisfied, or at least let me easily navigate to the dependency fish so I can look at it easier.

**Comment by Ottermandias** [comment]
No, that's what the colors are for. You can circumvent mooch and intuition requirements in many cases via collectible glove or just keeping a fish hooked. The fish does not depend on any time, which is important because otherwise it would be shown as unavailable when it is totally feasible to catch it with the prepared buff/mooch.
This is just absolute data, the game has explicit flags for dependencies, and if a fish does not have any, I will not give it any artificial just because it depends on others. The color is just to make you aware of that.
