### ISSUE TITLE
Alarm Sound

### ISSUE THREAD

**Issue by jmickey** [Ottermandias/GatherBuddy#66]
Hey with the new update has the alarm sound been removed?

**Comment by Ottermandias** [comment]
No?

**Comment by jmickey** [comment]
Sorry, I should have been more specific with my query. 

In any case, I found my issue - The window defaulted to being too narrow, hiding the options for sound and chat message. 

![image](https://user-images.githubusercontent.com/7720995/156901008-83fdc47a-d200-4ac5-8561-3570ea012a51.png)

Sorry to bother!

**Comment by Ottermandias** [comment]
No worries. It should show a vertical scroll bar though if it's too narrow.
But I noticed that there's nothing that says "Sound" per default, because the field says "None" and only says Sound-related stuff if you click on it or hover it. I'm gonna change the "None" to "No Sound" just to be sure, too :)
