### ISSUE TITLE
not teleporting or equipping gear when clicking on item to be gathered

### ISSUE THREAD

**Issue by wingnut1979** [Ottermandias/GatherBuddy#90]
Prior to this latest patch, I had my gather window setup with the stuff I collect a lot of.
I could just click the name of an item in that window, my gear for the appropriate job would get equipped - and then I'd get teleported to the nearest aetheryte - and there'd be a flag on the map of where to go.

Today...  I can sit here and click things until I turn blue - nothing happens.
Even typing in /gatherbuddy does not open the main window.
I can get the main window open by going into dalamud plugins and clicking the little cogwheel for gatherbuddy.
Clicking the items is equally ineffective as when using my gather window.
I discovered that if I click the name of the aethryite next to the item to be gathered, it then teleports me.

Am using version 3.0.6.0

Happy to supply any other info as needed

**Comment by wingnut1979** [comment]
1 addendum:

I first started using GB during 6.0
When 6.1 dropped, after dalamud was updated, my plugins (including GB) were all still happily installed.
I merely had to update them and was good to go.

Today with 6.11.. 
After dalamud updated, my other two plugins remained installed - but GB was no longer in my list of installed plugins.
I had to search for it and install it fresh.
Once installed, it automatically loaded up my old gather windows.

**Comment by Ottermandias** [comment]
Have you restarted after GatherBuddy was reinstalled?
It sounds like GatherBuddy could not register its chat command handler, and functionality for /gather is based on /gatherbuddy slash commands.
If your not-visible GatherBuddy crashed during boot (which it did when it was not updated not banned) it registered the chat commands and never unregistered them, so that the reinstalled version could not register them.
A simple restart should solve this.

**Comment by wingnut1979** [comment]
Yeah I tried restarting the game - no change.
For what it's worth, I have the exact same issue (exact same sequence of events too) on a 2nd computer.

**Comment by Ottermandias** [comment]
Do you perchance have any remnants of GatherBuddy in devPlugins or anywhere? You could try just going into installedPlugins and deleting the entire GatherBuddy folder there and then reinstalling, too.
Otherwise, can you please send me your %appdata%\XIVLauncher\dalamud.log   (note that if known extensions are hidden it might appear as just 'dalamud', please do not send 'dalamud.log.old' :) )

**Comment by wingnut1979** [comment]
You gave me some ideas and I started tinkering....

Right click on the plugin in the Dalamud listing.. "Reset plugin settings & reload" made everything start working on 1 computer. Will try other one when I wake up tomorrow (ugh.. it's almost 6am.. when I wake up later today).
Kinda sucks that I'll lose all my config.... but oh well... life is hard.

If you still want the Dalamud logs I can provide em.
But I'm also more than willing to call it good at this point (assuming other computer works too).

Much appreciate your time :)

**Comment by Ottermandias** [comment]
Well, if that works and you don't mind losing the config, sure.

**Comment by ggscott** [comment]
Adding that I have the same issue, however happy to help troubleshoot as oppose to resetting.
[dalamud.log](https://github.com/Ottermandias/GatherBuddy/files/8598133/dalamud.log)

**Comment by wingnut1979** [comment]
wasn't gonna come back and post here since it got closed.
doing the reset was only a temporary fix.
issue returned after opening game again.

however, going into the plugin folder and deleting the gatherbuddy folder -> then re-adding gatherbuddy once I got back into game was the actual real fix
bonus was that my settings survived that process (i guess settings are held elsewhere)

**Comment by Ottermandias** [comment]
Okay according to that log it always loads GatherBuddy twice. The first time it loads an outdated version before the necessary recompile after a signature in clientstructs changed, which crashes during construction, but after registering the slash commands.
The second time it loads the correct version, but can not register the slash commands, because they were registered and not unregistered.
So when you now manually disable and reenable it, the commands from the first are unregistered by the second, and the third can register them just fine so that it works.
Can you check if you somehow have two GatherBuddy.dll s in your installedPlugins folder (or in devPlugins, I guess)?

**Comment by wingnut1979** [comment]
Interesting.
So as stated before, I have two computers - both of which were exhibiting the same behavior.
I fixed one of them (via simply deleting the GatherBuddy directory within installedPlugins.

I have not yet fixed the other one.
On that one I have two directories:
3.0.5.1
3.0.6.0
Both of which contain GatherBudy.dll

**Comment by Ottermandias** [comment]
The first one was banned by goat (which was funny because I already PR'd the update before he banned it :D )
and I assume it could not be deleted while updating if you loaded it before the ban and before the update due to still being in use (because the commands were still registered).

**Comment by wingnut1979** [comment]
lol....
So basically a human-induced race condition.
